<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>02c1a579-9dbf-45a3-905b-b32a52e2b1eb</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_ch_i_m_b</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/main[1]/div[1]/div[1]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[href][title='Đồ\ Chơi\ -\ Mẹ\ \&amp;\ Bé']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'styles__StyledItem-sc-oho8ay-0 bzmzGe') and equals(@title,'Đồ Chơi - Mẹ &amp; Bé')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>styles__StyledItem-sc-oho8ay-0 bzmzGe</value>
        <webElementGuid>d13b1ed6-d865-4484-b479-19508efe80c2</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Đồ Chơi - Mẹ &amp; Bé</value>
        <webElementGuid>458b693b-d33e-46b5-9469-d0270b7c01a3</webElementGuid>
    </webElementProperties>
</WebElementEntity>