<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1058f5d8-2293-4426-b9e0-3e5deea62804</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_tka_tiki_vn_pixel_pixel</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/main[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[href='\/\/tka\.tiki\.vn\/pixel\/pixel\?data\=SmQ5zTOI_Z-JvNZRNeL5vj-yJXEg8NB6MmAJ7hJkRYQJSlhbupe4xwZBx64aB-0O4FzBodr3NfW2gGPWksUPQNR5hB7AIbk6GnD9z8mfnYam2hkxpB5qKfQIGHnbyn9hyFR7dyJbpKe1Q3SiqzYOFfKpq837ZsZs9cKXP8CrRKEDGxDriGppbY2UrJ1J6lQTnOfEZVPFoSqsnggw301LTKX6ztNX2n2qMBDIoc8mR7AdSfsEwyu5p9DXJH9tPnElM02rmXFOU-N93VK-5yYYdq9F72Oz6X3DGslL5zIyt7p6QSQvOWb7bFPDQwIS2HYQKcqQGk4nNtlgMnLrIcZkfhP5cBq8QHlqvCgsmNTFc_dX7HW9w9bmDFGtx85XueqcRgGZuiCOt0okv2JkjB_Jd3oBX8sOtoPYTst_8XtpPAowF6bwMsCXeiA2cjAB6GhcSB6kzvKlor7jD58GXUyun4T54P4CEar72Wvoe2AtqiuU-L8dG_SUXkEYLgQ5vwRK2TtINQUsUGPt42GMI7m4irN5fgdon3w_teS_cHHjViqjYFrvw3regnAIzaWmP9cVlC69eK5zsHo4HcDNrup9pjdzy6DIfsPkLxmhfwwM7WE3Fwir46XyY4xmw3Y9Wb1tkkn6FppSK2ohhn34tEKL8FVuFaaSO9kqOtOnEMsp68VJS8VyyGGB-TQfBMccLGbFaXivw5FV8lXmvYhY9jH2T6etqHRGgTnZrukSr9vlE69vqPDedTCmqO4xr6fnlFZ2WRsCl0-wIkOHAJrJaUIgwPKqMJp4eBjzm_l5Pkn6X3D1evkqJnmoRj21qAEYYVF1I7LYHZSp30wwQzm1ET0iva36xC8V_keLdAu757e411oPSqaLeFdaLTtqDqRYGpScfRJEoJz2xRfV_0NaphzkOT9KEvvzgRWf83CJ2HHTvoW9o2jxUyrqvC7N6wt6afYzVPlm7bzuEdEC3R3N0EzK-o_P6cSaiVz1BmxBjBySinNUzXDfT3pEWJaLIwW725XlPiqU4fXTE6hzv1vA4m_ODH1guUMgv-4CLFuFXwhH8ZgtAc27lgREImJ4R_Saqu3V3aEo9PY8Lo4q4zdJNzbgBZk0Fh9cezOjCNjFgWuwyPJ5NTS2Kb8I9NQArGLeW1HnAEW9IV7Fb3FFZAB73gcFizTObJbjjrGiyfyT9yNt91GN3VdV2ZCG3kzjb-KQz7WrdcTVNycBY13Ve--InWQYGqEKfPIa_JvRbfnRh9zzwr8h89JtxuGUgp6eL2CxoaWGxL_w-E6_CD1jp6EKRY1parU63RJvwWYqD4PYgmr2AfeWKD3jpsLP4JaeRCKUCVC4AcD0mHWJQWuevFM2WnOYU4tQ7mRkFYNAUmcJnSd4u5ETWy7zA8Mh_BhX-a1Y60dNrWPdQA\&amp;reqid\=qFAEdrHDPy08cS8Q\&amp;type\=CLICK\&amp;pos\=1']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'style__ProductLink-sc-7xd6qw-2 fHwskZ product-item')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>style__ProductLink-sc-7xd6qw-2 fHwskZ product-item</value>
        <webElementGuid>0d49e0fe-5268-4d3c-96b6-572c1d1fe9ad</webElementGuid>
    </webElementProperties>
</WebElementEntity>